In [27]:
import numpy as np
import tensorflow as tf
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Input,Conv1D,GlobalMaxPooling1D,Dense


from sklearn.model_selection import train_test_split
from sklearn.metrics import (accuracy_score,confusion_matrix,classification_report)
import matplotlib.pyplot as plt

In [35]:
X =np.array([
    [[3],[3],[3],[3],[3],[3],[3]], # efficient (low usage)
    [[3],[3],[3],[3],[3],[3],[3]], # efficient (low usage)
    [[7],[7],[7],[7],[7],[7],[7]], # not efficient (high usage)
    [[7],[7],[7],[7],[7],[7],[7]], # not efficient (high usage)
    [[8],[8],[8],[8],[8],[8],[8]]

],dtype="float32")

y =np.array([1,1,1,0,0],dtype="float32")
print(X.shape,y.shape)


(5, 7, 1) (5,)


In [36]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)
print(X_train,X_test)

[[[8.]
  [8.]
  [8.]
  [8.]
  [8.]
  [8.]
  [8.]]

 [[7.]
  [7.]
  [7.]
  [7.]
  [7.]
  [7.]
  [7.]]

 [[3.]
  [3.]
  [3.]
  [3.]
  [3.]
  [3.]
  [3.]]

 [[7.]
  [7.]
  [7.]
  [7.]
  [7.]
  [7.]
  [7.]]] [[[3.]
  [3.]
  [3.]
  [3.]
  [3.]
  [3.]
  [3.]]]


In [37]:
model  = Sequential([
    Input(shape=(7,1)), # 7 time steps, 1 feature
    Conv1D(4,3,activation="relu"), # 4 filters, kernel size of 3
    GlobalMaxPooling1D(), # global max pooling to reduce dimensionality
    Dense(1,activation="sigmoid") # output layer for binary classification
])





In [38]:
model.compile(loss="binary_crossentropy",optimizer="adam",metrics =["accuracy"])

In [39]:
history = model.fit(
    X_train,y_train,
    epochs=50,
    verbose=0
)

In [40]:
y_probs = model.predict(X_test,verbose=0).ravel()
print("pridicted probabilities:",y_probs)

thresold = 0.5
y_preds = (y_probs >= thresold).astype("int")
print("predicted labels:",y_preds)
print("the classes",y_test)

pridicted probabilities: [0.49368408]
predicted labels: [0]
the classes [1.]


In [41]:
acc = accuracy_score(y_test,y_preds)
print("accuracy:",acc)

cm = confusion_matrix(y_test,y_preds)
print("confusion matrix:\n",cm)

print("classification report:\n",classification_report(y_test,y_preds,target_names=["not efficient","efficient"]))



accuracy: 0.0
confusion matrix:
 [[0 0]
 [1 0]]
classification report:
                precision    recall  f1-score   support

not efficient       0.00      0.00      0.00       0.0
    efficient       0.00      0.00      0.00       1.0

     accuracy                           0.00       1.0
    macro avg       0.00      0.00      0.00       1.0
 weighted avg       0.00      0.00      0.00       1.0



c:\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMet